In [ ]:
!pip install datasets evaluate pandas sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install transformers==4.28.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install --upgrade huggingface_hub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from huggingface_hub import notebook_login

notebook_login()

In [ ]:
from transformers import AutoTokenizer, DataCollatorWithPadding
from datasets import load_dataset
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
label2id = {'Groceries': 0,
 'Shopping': 1,
 'Restaurants': 2,
 'Transportation': 3,
 'Travel': 4,
 'Entertainment': 5,
 'Utilities': 6,
 'Health': 7,
 'Services': 8,
 'Transfers': 9,
 'Cash': 10,
 'General': 11,
 'Insurance': 12,
 'Investment': 13,
 'Gifts': 14,
 'Charity': 15,
 'Others': 16
}


id2label = {
  0: "Groceries",
  1: "Shopping",
  2: "Restaurants",
  3: "Transportation",
  4: "Travel",
  5: "Entertainment",
  6: "Utilities",
  7: "Health",
  8: "Services",
  9: "Transfers",
  10: "Cash",
  11: "General",
  12: "Insurance",
  13: "Investment",
  14: "Gifts",
  15: "Charity",
  16: "Other",
}

In [ ]:
encoded_dict = label2id

In [ ]:
encoded_dict

{'Groceries': 0,
 'Shopping': 1,
 'Restaurants': 2,
 'Transportation': 3,
 'Travel': 4,
 'Entertainment': 5,
 'Utilities': 6,
 'Health': 7,
 'Services': 8,
 'Transfers': 9,
 'Cash': 10,
 'General': 11,
 'Insurance': 12,
 'Investment': 13,
 'Gifts': 14,
 'Charity': 15,
 'Others': 16}

In [ ]:
df = pd.read_csv("vendor_operation_categories_labelling.csv", )
df["text"] = df["entry"]
df["label"] = df["transaction_category"]
df = df.drop(['entry', 'transaction_category'], axis=1)

In [ ]:
df

text           label
0            MARKUP FEES CAIRO       Utilities
1                 Cash Deposit            Cash
2               ATM WITHDRAWAL            Cash
3              Credit Interest      Investment
4    PAYMENT RECEIVED INTERNET       Transfers
..                         ...             ...
207         AMAZON MARKETPLACE        Shopping
208                       Uber  Transportation
209                      APPLE         General
210                   MCDONALD     Restaurants
211        ALMOKHTABAR MEDICAL          Health

[212 rows x 2 columns]

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.dropna(subset=["label"], inplace=True)

In [ ]:
df = df.loc[:, ["text", "label"]]

In [ ]:
df

text           label
0            MARKUP FEES CAIRO       Utilities
1                 Cash Deposit            Cash
2               ATM WITHDRAWAL            Cash
3              Credit Interest      Investment
4    PAYMENT RECEIVED INTERNET       Transfers
..                         ...             ...
207         AMAZON MARKETPLACE        Shopping
208                       Uber  Transportation
209                      APPLE         General
210                   MCDONALD     Restaurants
211        ALMOKHTABAR MEDICAL          Health

[211 rows x 2 columns]

In [ ]:
df.label = df.label.map(encoded_dict)

In [ ]:
df

text  label
0            MARKUP FEES CAIRO      6
1                 Cash Deposit     10
2               ATM WITHDRAWAL     10
3              Credit Interest     13
4    PAYMENT RECEIVED INTERNET      9
..                         ...    ...
207         AMAZON MARKETPLACE      1
208                       Uber      3
209                      APPLE     11
210                   MCDONALD      2
211        ALMOKHTABAR MEDICAL      7

[211 rows x 2 columns]

In [ ]:
np.unique(df.label)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 16])

In [ ]:
train, test = train_test_split(df, test_size=0.2)

In [ ]:
test

text  label
147                  Alfa      0
122      Hawawshi El Refa      2
178                CIRCLE      0
41              GALAXYGYM      7
13        CASH BACK CAIRO      9
164               Myfawry      8
149         TELECOM EGYPT      6
15             Annual fee      6
19   ATM CARDLESS DEPOSIT     10
125  KANSAS FRIED CHICKEN      2
104                 JIMMY      2
148             McDonalds      2
119    LANYUAN RESTAURANT      2
54                 shiren      7
131        APPLE.COM/BILL     11
87               CHILLOUT      6
62         TRAFFIC MARKET      0
201                 Oscar      0
205        AMAN PASSPORTS      8
182                 QAHWA      2
166                Orange      6
127                  TBSW      2
110             STREET NO      2
36   BUFFALO WINGS AND RI      2
23    OTT SIDE BY SIDEMEN      5
121              FNTS JYM      7
14   Payment Direct Debit      9
83              dribrahim      7
134                 ALSHY      1
108              ETISALAT      6
98                SPOTIFY      5
109             STARBUCKS      2
0       MARKUP FEES CAIRO      6
196             MCDONALDS      2
118             EL MAQARR      8
146              My fawry      8
64              CAKE CAFE      2
153          GEIDEAMEDICA      7
188             BREADFAST      2
152            NAME CHEAP      8
128             HAG ARAFA      0
40               FLAMINGO      0
89     AIR FORCE HOSPITAL      7

In [ ]:
train.shape

(168, 2)

In [ ]:
test.shape

(43, 2)

In [ ]:
train

text  label
194            LAZADA      1
2      ATM WITHDRAWAL     10
117           ELMENUS      2
163         THE CREPE      2
22   Inward CO/ Funds      9
..                ...    ...
141             TOTAL      6
161      CHICKIN WORX      2
38              Udemy      8
180  FOOD AND COMPANY      2
61       KRISPY KREME      2

[168 rows x 2 columns]

In [ ]:
dataset = load_dataset("csv", data_files="renamed_vendor_operation_categories_labelling.csv", delimiter=",")["train"]

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset csv downloaded and prepared to /root/.cache/huggingface/datasets/csv/default-1933c2eb9ca5279c/0.0.0/6954658bab30a358235fa864b05cf819af0e179325c740e4bc853bcc7ec513e1. Subsequent calls will reuse this data.


  0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
dataset[0]

{'text': 'MARKUP FEES CAIRO', 'label': 6.0}

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
test.label.shape

(43,)

In [ ]:
train.label.shape

(168,)

In [ ]:
y_test.shape

(43, 12)

In [ ]:
y_train.shape

(168, 17)

In [ ]:
test["label"]

147     0
122     2
178     0
41      7
13      9
164     8
149     6
15      6
19     10
125     2
104     2
148     2
119     2
54      7
131    11
87      6
62      0
201     0
205     8
182     2
166     6
127     2
110     2
36      2
23      5
121     7
14      9
83      7
134     1
108     6
98      5
109     2
0       6
196     2
118     8
146     8
64      2
153     7
188     2
152     8
128     0
40      0
89      7
Name: label, dtype: int64

In [ ]:
test.shape

(43, 2)

In [ ]:
train.shape

(168, 2)

In [ ]:
np.unique(train.label)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 16])

In [ ]:
y_test = to_categorical(test.label)
y_train =  to_categorical(train.label)

In [ ]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
dataset = dataset.train_test_split(test_size=0.2)

In [ ]:
import torch.nn.functional as Fun

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 169
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 43
    })
})

In [ ]:
dataset["train"][0]

{'text': 'MEKKA', 'label': 16.0}

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased", problem_type="multi_label_classification")

def preprocess_function(examples):
    # Tokenize the texts
    return tokenizer(examples["text"], truncation=True)

In [ ]:
tokenized_datasets = dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/169 [00:00<?, ? examples/s]

Map:   0%|          | 0/43 [00:00<?, ? examples/s]

In [ ]:
tokenized_datasets["train"]

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 169
})

In [ ]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [ ]:
import evaluate

In [ ]:
accuracy = evaluate.load("accuracy")

In [ ]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    if len(labels.shape) == 2:
        labels = np.argmax(labels, axis=1)
    return accuracy.compute(predictions=predictions, references=labels)

In [ ]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=17, id2label=id2label, label2id=label2id
)

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForSequenceClassification: ['vocab_transform.bias', 'vocab_projector.weight', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.bias', 'classifier.weight', 'pre_classi

In [ ]:
training_args = TrainingArguments(
    output_dir="finbert",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    push_to_hub=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

In [ ]:
tokenized_datasets["train"][0]

{'text': 'MEKKA',
 'label': 16.0,
 'input_ids': [101, 2033, 15714, 102],
 'attention_mask': [1, 1, 1, 1]}

In [ ]:
tokenized_datasets["test"][0]

{'text': 'PROCAR',
 'label': 2.0,
 'input_ids': [101, 4013, 10010, 102],
 'attention_mask': [1, 1, 1, 1]}

In [ ]:
tokenized_datasets["train"].features["label"]

Value(dtype='float64', id=None)

In [ ]:
print(tokenized_datasets["train"]["text"][:10])

['MEKKA', 'PAYMENT RECEIVED INTERNET', 'FNTS JYM', 'LYCHEE FRUIT BAR', 'Credit Interest', 'BEANO', 'DIGITALOCEAN', 'ELDAHAN', 'AIR FORCE HOSPITAL', 'Outward Online Transfer']


In [ ]:
print(tokenized_datasets["train"].shape)

(169, 4)


In [ ]:
print(tokenized_datasets["test"].shape)

(43, 4)


In [ ]:
tokenized_datasets["train"]

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 169
})

In [ ]:
tokenized_datasets["test"]

Dataset({
    features: ['text', 'label', 'input_ids', 'attention_mask'],
    num_rows: 43
})

In [ ]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


ValueError: ignored